site_name: Snoco Makers Machine Information
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition

nav:
  - Home: "index.md"
  - 3D printers: 3Dprinters/index.md
  - Laser Cutters: LaserCutters/index.md