site_name: Snoco Makers Machine Information
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition

nav:
  - Home: "index.md"
  - 3D printers: 3DPrinters/index.md
  - Drag Knife: DragKnife/index.md
  - Laser Cutters: LaserCutters/index.md
  - Metal Shop: MetalShop/index.md
  - Wood Shop: Woodshop/index.md